version: "3.5"
services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:centos-5.0-latest
    # build: ./build/zabbix-server-pgsql-pyzabbix
    restart: always
    volumes:
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
    links:
      - postgres-server:postgres-server
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    env_file:
      - .env_db_pgsql
      - .env_srv
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - postgres-server
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-server
          - zabbix-server-pgsql
          - zabbix-server-centos-pgsql
          - zabbix-server-pgsql-centos
      zbx_net_frontend:
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.description: "Zabbix server with PostgreSQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "pgsql"
      com.zabbix.os: "centos"

  zabbix-proxy-sqlite3-vpoller:
    #  image: zabbix/zabbix-proxy-sqlite3:centos-5.0-latest
    # image: djettah/zabbix-proxy-sqlite3-vpoller:centos-5.0-latest
    restart: always
    build: ./build/zabbix-proxy-sqlite3-vpoller
    volumes:
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
    links:
      - zabbix-server:zabbix-server
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    env_file:
      - .env_prx
      - .env_prx_sqlite3
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-proxy
          - zabbix-proxy-sqlite3
          - zabbix-proxy-centos-sqlite3
          - zabbix-proxy-sqlite3-centos
      zbx_net_frontend:
    stop_grace_period: 30s
    labels:
      com.zabbix.description: "Zabbix proxy with SQLite3 database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-proxy"
      com.zabbix.dbtype: "sqlite3"
      com.zabbix.os: "centos"

  vpoller-proxy:
    # image: djettah/zabbix-proxy-sqlite3-vpoller:centos-5.0-latest
    restart: always
    build: ./build/vpoller-proxy
    links:
      - zabbix-proxy-sqlite3-vpoller
    env_file:
      - .env_vpoller_prx
      - .env_vfzsync
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 300s
      timeout: 15s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_backend:
      zbx_net_frontend:
    stop_grace_period: 10s

  zabbix-web-apache-pgsql:
    image: zabbix/zabbix-web-apache-pgsql:centos-5.0-latest
    restart: always
    links:
      - postgres-server:postgres-server
      - zabbix-server:zabbix-server
    volumes:
      - ./zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
    env_file:
      - .env_db_pgsql
      - .env_web
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - postgres-server
      - zabbix-server
    healthcheck:
      test: ["CMD", "curl", "-kf", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-web
          - zabbix-web-apache-pgsql
          - zabbix-web-apache-centos-pgsql
          - zabbix-web-apache-pgsql-centos
      zbx_net_frontend:
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.description: "Zabbix frontend on Apache web-server with PostgreSQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "apache2"
      com.zabbix.dbtype: "pgsql"
      com.zabbix.os: "centos"

  # zabbix-agent:
  #   image: zabbix/zabbix-agent:centos-5.0-latest
  #   ports:
  #     - "10050:10050"
  #   volumes:
  #     - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
  #     - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
  #     - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
  #     - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  #   links:
  #     - zabbix-server:zabbix-server
  #   env_file:
  #     - .env_agent
  #   user: root
  #   privileged: true
  #   pid: "host"
  #   networks:
  #     zbx_net_backend:
  #       aliases:
  #         - zabbix-agent
  #         - zabbix-agent-passive
  #         - zabbix-agent-centos
  #   stop_grace_period: 5s
  #   labels:
  #     com.zabbix.description: "Zabbix agent"
  #     com.zabbix.company: "Zabbix LLC"
  #     com.zabbix.component: "zabbix-agentd"
  #     com.zabbix.os: "centos"

  postgres-server:
    image: postgres:12
    restart: always
    volumes:
      - ./postgres_env/data:/var/lib/postgresql/data:rw
    env_file:
      - .env_db_pgsql
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    stop_grace_period: 1m
    command:
       - "postgres"
       - "-c"
       - "shared_buffers=3GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U `cat /run/secrets/POSTGRES_USER` -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_backend:
        aliases:
          - postgres-server
          - pgsql-server
          - pgsql-database

  grafana:
    image: grafana/grafana:7.0.3-ubuntu
    restart: always
    links:
      - zabbix-web-apache-pgsql:zabbix-web
    volumes:
      - ./grafana_env:/var/lib/grafana:rw
    env_file:
      - .env_grafana_prod
    secrets:
      - GRAFANA_PASSWORD
    healthcheck:
      test: ["CMD", "curl", "-kf", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_frontend:
      zbx_net_backend:

  vfzsync:
    image: djettah/vfzsync:test
    # build: .
    restart: always
    links:
      - zabbix-server:zabbix-server
      - zabbix-web-apache-pgsql:zabbix-web
      - zabbix-proxy-sqlite3-vpoller:zabbix-proxy
      - vpoller-proxy:vpoller-proxy
    env_file:
      - .env_vfzsync
    healthcheck:
      test: ["CMD", "curl", "-kf", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_frontend:
      zbx_net_backend:

  nginx:
    image: nginx:1.17
    # build: ./build/nginx_env
    restart: always
    volumes:
      - ./nginx_env/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./zbx_env/etc/ssl/apache2:/etc/nginx/cert:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - grafana:grafana
      - vfzsync:vfzsync
      - zabbix-web-apache-pgsql:zabbix-web
      - zabbix-proxy-sqlite3-vpoller:zabbx-proxy
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_frontend:
      zbx_net_backend:


  # autoheal:
  #   image: willfarrell/autoheal
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     AUTOHEAL_CONTAINER_LABEL: all
    

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24


secrets:
  POSTGRES_USER:
    file: ./.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./.POSTGRES_PASSWORD
  GRAFANA_PASSWORD:
    file: ./.GRAFANA_PASSWORD
